### ISSUE TITLE
Tracker for ArcGIS_AGOL 

### ISSUE THREAD

**Issue by dimp8634** [dimp8634/L10N_QAVendor_TC#139]
- [ ] Sign into the application
    - If the user has a tracker license they should be signed in
    - If the user does not have a tracker license they should be shown an error message
    - If Tracking has not been enabled on the portal they should be shown an error message
- [ ] Enable tracking
- [ ] Collect tracks to ensure that the tracks are rendered
- [ ] Tap on a track to make sure the proper coordinates and date format are shown
- [ ] Open settings and enable Dark Mode
- [ ] Manually upload the tracks
- [ ] Sign out
